apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_948098db9084
          # env:
          #   - name: DATABASE_URL
          #     value: jdbc:mariadb://mariadb:3306/krampoline
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /test
              port: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000